language: ruby
sudo: false
rvm:
- 2.3.4
addons:
  apt:
    packages:
    - aspell-pt-br
cache: bundler
script: bundle exec rspec spec && bundle exec middleman build --verbose
deploy:
  skip_cleanup: true
  provider: script
  script: bundle exec middleman deploy
  on:
    branch: master
