language: ruby
sudo: false
rvm:
- 2.3.4
addons:
  apt:
    packages:
    - aspell-pt-br
cache: bundler
script: bundle exec rspec spec && bundle exec middleman build --verbose
deploy:
  skip_cleanup: true
  provider: pages
  repo: ember-brasil/ember-brasil.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN
  github_url: ember-brasil.com.br
  local_dir: ./build
  on:
    branch: master
